services:
  db:
    image: postgres:17.0
    hostname: ${host}
    ports:
      - "5432:${port}"
    environment:
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_USER=${user}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
